### ISSUE TITLE
Particles near boundaries possible Bug and related feature request

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#68] opened 2018-02-18 09:25 UTC
Hi,

Two images below - surface mesh and particles - all render diffuse.

I am trying to have as few particles (ideally none) near the boundary edge
I have set behaviour and boundary to be kill for all axis for foam/bubble/spray

I also have set enable emission near boundary to false.

However as you can see from the image I still have foam near the boundary.

So perhaps I am misunderstanding the settings or perhaps there is a bug.

Possible related new features:
1.  would it be possible to set a distance from boundary to kill particles rather than just the edge?
2.  would it be possible to set a distance from boundary for (enable emission near boundary) to work on?
3.  if they are possible then is it possible to perhaps introduce boolean geometry operators to kill particles in?

The reasoning here is that it would help with compositing as it is generally the edges of the domain that (at least I) won't be keeping.

Also - in this secene I also have boundary friction set to 1 - are my spikes splashes caused by the boundary being 1 and water near by compressing into it?

Thanks for any info/help.

![bug2](https://user-images.githubusercontent.com/36420510/36350273-ad25f3c6-148d-11e8-8b95-f607785b20fb.JPG)

![bug1jpg](https://user-images.githubusercontent.com/36420510/36350272-a91782cc-148d-11e8-902f-fdc5e08c61ee.JPG)

**Comment by RevDr** [comment] 2018-02-19 20:41
Attached a version of the file for you.

Using outflow sounds a good idea.  Hadn't considered that.  

Does outflow work when particle goes outside the object or inside the object?  Whichever way could there be a switch to change the behaviour?

Probably won't get anywhere near as much testing done this week as my week off is over and have a very busy few days coming up.

[test2_4db.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1738117/test2_4db.zip)

**Comment by rlguy** [comment] 2018-02-19 23:06
Thanks for updating with the scene file!

**are my spikes splashes caused by the boundary being 1 and water near by compressing into it?**

It seems that the spikes are caused by the shape of the OceanGeoBake object:

![oceangeobake_mesh_splash](https://user-images.githubusercontent.com/4285191/36400316-0f4b2984-1585-11e8-81da-0e1415439857.jpg)

Fluid will flow into these gaps against the side of the domain and cause a splash.

**Does outflow work when particle goes outside the object or inside the object?**

Particles are removed when they are inside of the outflow object. 

**Whichever way could there be a switch to change the behaviour?**

That's a good idea and not to difficult to implement! I have opened a feature request for this (issue #80).

***

I will be closing this issue now. Thanks for spending so much time testing the addon and providing feedback!

**Closed by rlguy** 2018-02-19 23:06 UTC
