### ISSUE TITLE
Baking stops, "Out of Memory", inflow outside domain.

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids-Beta#123] opened 2018-02-23 13:16 UTC
![blender_2018-02-23_14-10-25](https://user-images.githubusercontent.com/8568089/36595687-72ddde1c-18a3-11e8-83a3-ed7a224dfe37.png)

Playing around with the full plugin for the first time and I seem to be getting stuck.
My first attempt is just to recreate an older scene I made with the normal Blender fluid solver.
But whenever the only object in the scene is done moving it just goes "Out of memory" at the same time.
It is not even a complex setup, resolution is only on 75.
![blender_2018-02-23_14-13-37](https://user-images.githubusercontent.com/8568089/36595759-c3a3b02e-18a3-11e8-9da8-447ac7ccb321.png)
The inflow object (the icosphere) dips down into the domain to create a drop, worked fine in Blender itself, as soon as the object goes back up outside it stops with Out Of Memory, making me believe thats the cause.

Things I tried so far include disabling GPU Scalar Field, GPU Particle Advection, setting the CPU/GPU Ratio to 0, setting fixed threads, closing and reopening Blender.
Nothing on my PC actually goes out of memory, RAM is half used, VRAM is not at max, HDD has more than enough space.

Scene: [01.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1751735/01.zip)
Scene seems to bake just fine if I let the inflow inside the domain, is this a problem with the inflow object going out the domain and staying there?

**Comment by rlguy** [comment] 2018-02-23 19:15
Thanks for reporting this! I have tested the scene and I get the same error. I will keep you updated on the fix in this issue.

**Comment by rlguy** [comment] 2018-02-23 19:56
This error has been fixed and will be included in the next version (**0.1.3b**). This was caused by a bug where when the inflow is too far outside of the domain, the simulator would try to reserve an invalid amount of memory which would trigger the 'Out of memory' error popup.

### Workaround

Until the next version is released, there is a workaround. This error only occurs when the object is at a certain distance outside of the domain. To prevent the error, make sure that when the object is outside the domain, that it is close enough to be barely touching the domain edge.

**Closed by rlguy** 2018-02-23 19:56 UTC
Labels: bug
