### ISSUE TITLE
Baking empty domain causes scripting error

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#143] opened 2018-02-24 12:40 UTC
Hi,

I know this is a pointless example - however, if I create a domain and put nothing in it and then bake the background scripts get a runtime error

AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\pyfluid\pybindings.py", line 30, in check_success
    raise RuntimeError(errprefix + str(libfunc()))
RuntimeError: FluidSimulation_update - b'basic_string::_S_create'

**Comment by rlguy** [comment] 2018-02-26 20:37
Hey, I'm not able to reproduce this error. An empty simulation runs to completion for me.

If anyone else is able to reproduce this issue, please let me know.

**Comment by rlguy** [comment] 2018-03-01 01:26
This bug has be fixed and will be included in the next version (**0.1.3b**).

This bug occurs when the total frame computation time is reported as 0 and causes some 'division by zero' errors. This bug depends on the speed of your system. I do most development on a laptop, so it wasn't fast enough for the timer to report 0 seconds and that is why I wasn't able to reproduce the bug earlier!

**Closed by rlguy** 2018-03-01 01:26 UTC
Labels: bug, help wanted
