### ISSUE TITLE
[Crash] With a particular object set to Obstacle, Blender crashes when baking sim

### ISSUE THREAD

**Issue by SimonCDalzell** [rlguy/Blender-FLIP-Fluids-Beta#91] opened 2018-02-21 14:48 UTC
Mind you I'm not great at 3D modeling, so chances are there is something really stupid about the model, but that's the point of having beta testers innit.

I've stripped down the project to just the sim and the offending object. The object was created in 3ds Max and exported via FBX, then brought into Blender.

If the ceiling object is set to Obstacle, the sim sometimes gets to "Baking in progress, initializing", then closes to desktop. Sometimes the close is immediate when clicking "Bake".

Edit: Forgot to mention that no temp files are generated. Is there a separate log I should provide? Is there documentation somewhere on useful files to include when reporting bugs?

[SimonCDalzell ConcertHallFloodCrash.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1744353/SimonCDalzell.ConcertHallFloodCrash.zip)

**Comment by rlguy** [comment] 2018-02-21 19:14
Hey SimonCDalzell,

Thanks for reporting this and providing a scene to for me to test with!

The crash was caused by loose geometry (vertices with no faces connected) in the ceiling mesh. This is now fixed and will be included in the next version (**0.1.2b**).

### Workaround

Until the next version is released, a workaround is to delete loose geometry in the mesh:
1. Enter edit mode on the obstacle
2. Select loose geometry (Select > Select All By Trait > Loose Geometry)
3. Delete selected vertices

![loose_geometry](https://user-images.githubusercontent.com/4285191/36499838-5742fa28-16f7-11e8-9aae-5355bee53916.jpg)

### Scene Notes

You may have trouble using an obstacle this thin in your simulation. The simulation works on a grid, and if the obstacle is too thin, it may not show up effectively on the simulation grid. This will cause fluid to slip through the obstacle. Some fixes for this include:
1. **Increase domain resolution** - This will increase grid detail to help the object show up better in the simulation
2. **Increase obstacle thickness** - A thicker obstacle will show up better on the simulation grid
3. **If possible, use a thick object for simulation and the thin object for rendering** - This depends on what kind of animation you are trying to achieve
4. **Reduce the CFL Safety Factor number in the ([Advanced Panel](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings))** - This will limit how far fluid can move in a time step and may prevent fluid from passing through the obstacle

***

Hope this clears some things up! I'll be closing this issue now. Let me know if you have any other questions.

**Closed by rlguy** 2018-02-21 19:14 UTC
Labels: bug, crash
