### ISSUE TITLE
[Test Case Results] Guitartom47

### ISSUE THREAD

**Issue by guitartom47** [rlguy/Blender-FLIP-Fluids-Beta#5] opened 2018-02-14 03:43 UTC
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1722543/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment] 2018-02-14 05:28
Thanks guitartom47!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Closed by rlguy** 2018-02-14 05:28 UTC

**Comment by guitartom47** [comment] 2018-02-14 16:11
Hi, Ryan!
Well, I have a few questions - but first good luck with this project. My first impression is that it looks great. I have downloaded the new build.
1. Since the issue is closed, does that mean I should open a new issue when I post test case results? (I'm ignorant of how GitHub works I'm afraid.)
2. In the new build, the test cases don't seem to have the zip file report button but do have a CSV. Is that what you'd like to see?
3. I notice that settings are now fully manual with no preset buttons for resolution. Should I just play with different resolutions - and push the limits -  and send reports? 
4. Should I just play with the test cases, or can I try my own scenes?
5. I have two other Windows 10 Nvidia GPU computers that might be helpful to test the product with. Should I just stick with my original PC for now?

Thanks for allowing me to beta test this great product,
Tom Allen
 

    On Tuesday, February 13, 2018 11:28 PM, Ryan Guy <notifications@github.com> wrote:
 

 Thanks guitartom47!I checked your results and it looks like the test ran without errors.I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.I will be closing this issue. Please post any further test case results to this thread.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by rlguy** [comment] 2018-02-14 17:29
Hey guitartom47!

**1. Since the issue is closed, does that mean I should open a new issue when I post test case results? (I'm ignorant of how GitHub works I'm afraid.)**

You should post all of your future test case results to this thread. This thread will be kept closed, but you can still post to it. Don't worry about being new to GitHub, there are many other beginners here too!

**2. In the new build, the test cases don't seem to have the zip file report button but do have a CSV. Is that what you'd like to see?**

The full beta version does not have the 'Export Test Case' button. We are only taking test case results from the pre-defined scenes with the test suite addon. If you want to run more test cases, you will need to reinstall the test suite addon.

**3. I notice that settings are now fully manual with no preset buttons for resolution. Should I just play with different resolutions - and push the limits -  and send reports?**

The full beta version allows you to do whatever you want with the addon. If you run into any problems, open up a bug report.

**4. Should I just play with the test cases, or can I try my own scenes?**

You can try out the test cases, or try out making your own scenes. You're free to test the addon however you like.

**5. I have two other Windows 10 Nvidia GPU computers that might be helpful to test the product with. Should I just stick with my original PC for now?**

You can test the addon on any computer that you want.  If you run test cases on other computers, you can still post the results here.

***

Hope this answered your questions, let me know if you have any others!
