### ISSUE TITLE
[Test Case Results] camcam2015

### ISSUE THREAD

**Issue by camcam2015** [rlguy/Blender-FLIP-Fluids-Beta#4] opened 2018-02-14 03:06 UTC
Results from the first test case:

[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1722465/test_case_viscous_net65.zip)

**Comment by rlguy** [comment] 2018-02-14 05:36
Thanks camcam2015!

I checked your results and it looks like the test ran okay, but it looks like there is a small issue with the simulator that should be fixed. The issue is that the addon is choosing to use your **Intel(R) HD Graphics 4600** chip instead of your **GeForce GTX 1070** GPU, which will cause simulations to run a bit slower. I'll open up an issue to fix this problem.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Closed by rlguy** 2018-02-14 05:36 UTC
Labels: Test Case
