### ISSUE TITLE
Baking Outside Domain

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#209] opened 2018-03-16 07:23 UTC
I have a simulation that when baked, the fluid object is firstly triple it's size and it's baking outside of the domain... Bit strange. I will email you guys the blend file!
![baking_outside_domain](https://user-images.githubusercontent.com/36161534/37508434-b0cdcabc-28fb-11e8-913c-0231f5dd7166.jpg)

**Comment by juangea** [comment] 2018-03-16 07:27
Does all the object have the Scale applied? This could be an error with scale not being applied in every object, domain, Flow, etc...

**Comment by k1ff** [comment] 2018-03-16 07:30
Yeah, all that jazz is applied

**Comment by rlguy** [comment] 2018-03-16 17:07
Hey,

I checkout out the .blend. It looks like the problem is that the scale of the fluid mesh object is set to **(3.5, 3.5, 3.5)**. The fix is to manually set the scale back to **1**.

I am not sure how the mesh object got into that state. Are you able to reproduce this issue with exact steps?

**Comment by Blaast** [comment] 2018-03-16 18:23
Issue related to an applied scale on the fluid mesh, approved, just had this issue.

**Comment by PavelBlend** [comment] 2018-04-04 17:54
I also caught this bug. But I can not reproduce it. The scale is the same. But the position is different:
![outside_baking](https://user-images.githubusercontent.com/7983249/38324887-2bbf3d2a-384a-11e8-967a-562a1cba8046.jpg)

**Comment by rlguy** [comment] 2018-04-04 19:46
Thanks for letting me know! I think I'll rework the way that mesh loading/transforms work. It looks like it might be better for me to calculate the transforms manually instead of using Blender methods so that I can make sure loading is correct 100% of the time.

**Comment by PavelBlend** [comment] 2018-04-07 13:12
I managed to reproduce the error again. Here are the exact steps:
https://youtu.be/9n9AVXj-24M
You need to delete the fluid_surface object and the new object fluid_surface will appear (after re-baking) in a different position and scale.

**Comment by lanmind01** [comment] 2018-04-09 02:46
I was struggling with this issue as well!

**Comment by rlguy** [comment] 2018-04-12 00:36
I have reworked how meshes are loaded and transformed. Meshes should now always load correctly. This fix will be included in the next version (**0.1.4b**).

**Closed by rlguy** 2018-04-12 00:36 UTC
Labels: bug
