### ISSUE TITLE
Whitewater outside domain when final frame is changed

### ISSUE THREAD

**Issue by alex3dpl** [rlguy/Blender-FLIP-Fluids-Beta#202] opened 2018-03-11 19:08 UTC
I was wondering why part of whitewater particles are rendering outside domain in my test. In found, that in some cases, when I changed final frame value (for example from 250 to 152), whitewater particles are rendering outside domain. Cache is not matching changed frame range or is something wrong with synchronizing objects when rendering - not sure.  In the viewport (full preview enabled) everything looks allright - there isn't any particle outside domain.

frame 90 with bug
![flip_fluid0090](https://user-images.githubusercontent.com/36315575/37257338-a219186e-2568-11e8-8045-f98e08f3c9dc.png)
frame 90 without bug
![flip_fluid0090_](https://user-images.githubusercontent.com/36315575/37257352-a791cc32-2568-11e8-93b8-9fd7b9770097.png)

**Comment by rlguy** [comment] 2018-03-13 19:20
Hey, is this bug repeatable? Does this happen every time in the same conditions? I've had this happen on rare occasions but could not reproduce the problem. I assumed it was an issue related to Blender/Cycles. The work around for me was to re-render the frame.

**Comment by alex3dpl** [comment] 2018-03-18 09:18
Hi, can't reproduce, but I'll try figure out.

**Comment by Blaast** [comment] 2018-03-28 16:23
Hi, I've had to change regularly on my current simulation the start and final frame, but it never occured to me (over 10 to 15 changes) !
How often is it happening for you ?

**Comment by rlguy** [comment] 2018-03-28 20:42
I'll be closing this issue. If you run into this problem with any more info, let me know and I'll reopen this!

**Closed by rlguy** 2018-03-28 20:42 UTC
