### ISSUE TITLE
Re-baking error?_

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#64] opened 2018-02-17 07:10 UTC
First, I have finished baking and got result.
After that, I changed properties, resolution, particle scale and turned off debugging.
Then, I re-baked.
Result is this,
![untitled2](https://user-images.githubusercontent.com/36343687/36338925-85b750ea-13fd-11e8-86fc-4b4cac2e8c4a.jpg)

Rendered image.
![untitled](https://user-images.githubusercontent.com/36343687/36338928-905e5656-13fd-11e8-9ba4-af25cb370927.jpg)

What should I do?

**Comment by rlguy** [comment] 2018-02-17 07:30
Hey,

This looks like something is definitely going wrong! Is this issue repeatable (Does the same thing happen if you re-bake)? Would you be able to attach the scene so I could test it out? You will need to create a .zip of the .blend to upload it to this issue.

**Comment by Toudou-Blender** [comment] 2018-02-17 08:47
Hi,

Yes, it is repeatable! Here is my operation step by step.
And I attached the zip file of the .blend file.

[Test2.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733520/Test2.zip)

(my steps)
1.Set object as domain.
2.Enable Whitewater emission.
3.Enable Presets and select Basic whitewater.
4.Enable Fluid Particles Debugging.
5.Select another object and set Fluid.
6.Bake it.
7.Select domain object.
8.Rest bake.
9.Increase grid resolution from 65 to 100.
10.Increase Subdivisions from 0 to 1.
11.Decrease particle scale from 1 to 0.2.
12.Turn off Fluid Particles Debugging.
13.Bake again.
14.That anomaly happened! The fluid is wired shape in the 3D view.
15.Stopped baking.

**Comment by rlguy** [comment] 2018-02-19 19:05
Hey Toudou-Blender, thanks for updating me!

The problem is caused by the **Particle Scale** setting. The particle scale determines how large the particles will be when generating the surface mesh. A value of 0.2 is generally too small. The fluid mesh is generated on a grid, and if the particles are too small, their data will not be able to show up on the grid reliably.

In general, the particle scale should not be set to a value less than 1.0. This may cause unreliable meshing or flickering in an animation.

I have added a 'soft minimum' value to 1.0 to the particle scale setting. This means that the user interface wont allow the user to drag the value below one, but if the user really wants a value less than one, they may explicitly enter a number value below one and the interface will allow it. This change will be included in the next beta addon version (v0.1.2b).

Hope this clears up the issue for you!

**Closed by rlguy** 2018-02-19 19:05 UTC

**Comment by Toudou-Blender** [comment] 2018-02-19 23:51
Thank you!
