### ISSUE TITLE
Inflow not emitting fluid when velocity is too large

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#82] opened 2018-02-20 05:03 UTC
See figure below. Left side is inflow velocity as -2m/s. Right side is inflow velocity as -4m/s.
Flow of the right didn't appear.
I seems that less than -3m/s can't work correctly.  I think.

![image](https://user-images.githubusercontent.com/36343687/36408037-24f0b9fe-1646-11e8-99e3-dc88b388617a.jpg)

**Comment by rlguy** [comment] 2018-02-20 05:05
Hey Toudou-Blender, would you be able to attach the .blend scene for me to test? You will need to compress the blend to a .zip file to attach it to this issue thread.

**Comment by rlguy** [comment] 2018-02-20 18:52
Hey Toudou-Blender,

Thanks for the .blend, I checked it out! The problem is that your domain is quite small, so a speed of 4m/s is very fast compared to the small size. With a speed that fast, the simulator is having trouble processing the inflow fluid and is deleting the fast fluid to prevent the simulation from becoming unstable. You can fix this by increasing the **Max Frame Substeps** settings in the **FLIP Fluids Advanced Panel**. This will allow the simulator to take more time to process the fast moving fluid and prevent the fluid from being removed from the simulation. Setting the max value to 20 should work.

Let me know if this works for you and if you have any other questions!

**Comment by Toudou-Blender** [comment] 2018-02-20 19:13
Thank you for the resolution.
I tried to set it to 20 and it works! 
This scene (the box) is created using real scale in meter, not blender unit.
I think that it is better to describe in somewhere about the increasing the Max Frame Substeps for real scaling scene? 
What do you think?

**Comment by rlguy** [comment] 2018-02-20 19:18
I agree that it needs some documentation. I am working on a 'troubleshooting' documentation page for these types of common problems. Issues like these help me figure out what kind of problems users are having and let me know what to put on that page.

I just noticed you have whitewater enabled, so here's a tip: The whitewater default settings are set to work well on large domains (5m+ in size). For a smaller domain, you should adjust the [Min/Max Energy Speed](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Whitewater-Settings) settings to better suit the velocities in your smaller scale simulation. I would suggest trying a min-max values of 0.1 and 3.0. This will trigger more whitewater particles to be generated.

**Comment by Toudou-Blender** [comment] 2018-02-20 20:10
Thank you for the suggestion.
I set it.

On the other hand, when I rendered this scene, the whitewater rendered so big.
I think that it may be caused by smaller domain size, too.
Is there a solution to be smaller the whitewater except to make the domain bigger (leave domain size as it is)?
![result0](https://user-images.githubusercontent.com/36343687/36446621-41b2669e-16c5-11e8-8a4f-64f72bd6af35.jpg)
![result](https://user-images.githubusercontent.com/36343687/36446629-454fc904-16c5-11e8-9da5-29c4eeb970ba.jpg)

**Comment by rlguy** [comment] 2018-02-20 20:42
In the [FLIP Fluid Display Settings](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Display-Settings) panel, you can lower the particle **scale** value for smaller whitewater particles:

![particle_scale](https://user-images.githubusercontent.com/4285191/36448077-3efe75e4-163b-11e8-99d2-58c3585537a3.jpg)

**Comment by Toudou-Blender** [comment] 2018-02-20 20:59
Oh! Thank you!
I need to learn more.

**Comment by rlguy** [comment] 2018-02-20 21:02
No problem! There are a lot of settings to learn about in this addon.

I'll be closing this issue now. Let me know if you have any other questions.

**Closed by rlguy** 2018-02-20 21:02 UTC
Labels: scene troubleshooting
